import json
import os
from config import (
    MONGO_URL, OWNER_ID,
    MAX_FILE_SIZE, MAX_UPLOADS_PER_HOUR, MAX_UPLOADS_PER_DAY,
    UPLOAD_COOLDOWN, DEFAULT_STORAGE_QUOTA, MAX_SHARE_LINKS,
    MAINTENANCE_MODE, DATABASE_NAME,
)

RATE_LIMITS = {
    "saved": 5,
    "get": 3,
    "genlink": 10,
    "login": 5,
    "register": 3,
    "search": 3,
}

PIN_LOCK_ATTEMPTS = 3
PIN_LOCK_DURATION = 600
PIN_DAILY_LOCKOUT_ATTEMPTS = 10
PIN_DAILY_LOCKOUT_DURATION = 86400

LOGIN_LOCK_ATTEMPTS = 5
LOGIN_LOCK_DURATION = 1800

SPAM_WARNINGS = 1
SPAM_MUTE_DURATION = 600
SPAM_BAN_DURATION = 86400

CLOUD_DB_NAME = DATABASE_NAME


def _load_maintenance():
    return MAINTENANCE_MODE


def set_maintenance(enabled):
    pass
